import Head from 'next/head'
import Banner from '../components/Banner'
import Header from '../components/Header'
import Productsinfo from '../components/Productsinfo'



export default function Home({products}){
  return (
    <div className=' bg-white'>
      <Head>
        <title>amazon nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className='max-w-screen-2xl mx-auto bg-gray-200'>
      <Banner />
      <Productsinfo products={products}/>
      </div>
    </div>
  )
}

export async function getServerSideProps () {
const  products= await fetch('https://fakestoreapi.com/products').then(
  (res)=> res.json()
)
return{
  props:{
    products,
  }
}
}

